
#Makefile for Assignment 2: Sudoku
#Author: Hayden Nanney & Brayden Faulkner
#Date: 2/4/2020

CC = gcc
EXE = sudoku

$(EXE): main.o
	$(CC) -o $(EXE) main.o -I.

clean:
	-rm -f *.o *~ $(EXE)